name: Docker

run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on:
  workflow_call:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v2.7.0
      
    - name: Docker Login
  # You may pin to the exact commit or the version.
  # uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
      uses: docker/login-action@v2.2.0
      with: 
    # Username used to log against the Docker registry
        username: gmartins882
    # Password or personal access token used to log against the Docker registry
        password: ${{ msecrets.PASSWORD_DOCKER_HUB }}
